name: Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist/
